replicaCount: 1

image:
  repository: romilsingal2024/react-frontend
  tag: v1.0.1
  pullPolicy: IfNotPresent

#env:  # Move env to the top level
  #REACT_APP_BACKEND_URL: "http://172.18.0.2:32001"
frontend:
  config:
    REACT_APP_BACKEND_URL: "http://mybackend-service:5000"
backend:
  repository: romilsingal2024/flask-backend
  tag: v1.0.1
  env:
    POSTGRES_HOST: "mypostgres-service"
    POSTGRES_PORT: "5432"


postgresql:
  image: postgres:latest  # Official PostgreSQL image
  
# Define secret values for PostgreSQL credentials
secrets:
  postgres:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "admin"
    POSTGRES_DB: "postgres"
service:
  type: ClusterIP
  ingressPort: 80
  frontendPort: 80
  backendPort: 5000
  dbPort: 5432
serviceAccount:
  create: true          # Set to false if you don't need a ServiceAccount created
  name: ""              # Name of the ServiceAccount (if empty, Helm will use the default name)
  annotations: {} 

ingress:
  enabled: true       # Set to true if you want to enable ingress
  annotations: {}      # You can add any annotations required for the ingress
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []              # TLS configuration (optional)
resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"
