pipeline {
    agent {
        kubernetes {
            // Define the pod template
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: nodejs
                image: node:18-alpine
                command:
                - cat
                tty: true
            """
            defaultContainer 'nodejs'
        }
    }
    
    stages {
        stage('Get a nodejs project') {
            steps {
                container('nodejs') {
                    script {
                        stage('Check Node.js Version') {
                            sh 'node --version'
                        }
                    }
                }
            }
        }
    }

}
